DELETE https://gobank-tamir-42opbff6wa-zf.a.run.app/account/66890330bbc5e687dee3595d
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjA1MTQ1MDYsInVzZXJJZCI6IjY2ODkwMzRhYmJjNWU2ODdkZWUzNTk1ZSIsInVzZXJuYW1lIjoidGVzdDIifQ.kUZq1q2oQo-zc8TOBh_Yx5igg2Zo66PZHo3n_RZA69k

