GET http://localhost:8080/account/6654d8d00010177f91aaa6d2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTY5MTg1NjksInVzZXJJZCI6IjY2NTVmY2E4MDMyOWQ5YTAxNjllZTgwNSIsInVzZXJuYW1lIjoidGFtaXJFeDIifQ.r5LI_znq8eUb9UYEdVh2aG5cT8lhMguAnDhwGUHpjU0

