GET http://localhost:8080/account/name/betyusha
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTc3MDIyNTksInVzZXJJZCI6IjY2NWUxOGY2NWE2ZWYwMmFkZjE2YWY1ZCIsInVzZXJuYW1lIjoiSmhvbiJ9.oZ8W7TxdHb8F3sN7taZfGzrxitjnTQd-hJPxKL-eNQs