GET https://localhost:5252/account/name/poatan
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjA4MDUxMzAsInVzZXJJZCI6IjY2NzE5YmNjODE2MTg4OGQxMTk5MDRlZSIsInVzZXJuYW1lIjoiRG9uQ29yIn0.MrhkbKBZKXdt5Oatd_CTlyQzz1m400AWvqKhUyUJTCY