POST http://localhost:8080/account/chatgpt
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTk1NTkzMDMsInVzZXJJZCI6IjY2NzE5YmNjODE2MTg4OGQxMTk5MDRlZSIsInVzZXJuYW1lIjoiRG9uQ29yIn0.uVhhMJnhyvAaplk8RPzwu7EoP4cUToonLRKxECiyTTs

{
    "user_text": "  find this account 667167eaafe345816d333b3d    "
}