POST http://localhost:8080/account/chatgpt
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg5ODA2ODQsInVzZXJJZCI6IjY2NzE5YmNjODE2MTg4OGQxMTk5MDRlZSIsInVzZXJuYW1lIjoiRG9uQ29yIn0.EjkSe0W6Kd-oT-aCvLuEmESL7xJixsmdKH_2va1SSFM

{
    "user_text": "  check this account balance 66719bcc8161888d119904ee "
}