POST http://localhost:8080/account/chatgpt
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg4MTIwMjYsInVzZXJJZCI6IjY2NWUxOGY2NWE2ZWYwMmFkZjE2YWY1ZCIsInVzZXJuYW1lIjoiSmhvbiJ9.BNVu6N0jo6nU_TQADua0ds_wnHgDuISd0wnXM7agLxM

{
    "user_text": " search for tommy phone number "
}