POST http://localhost:8080/login
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTczMTgzMjMsInVzZXJJZCI6IjY2NWMxNjkyZTU5MGM1ODdmNzE0MWU5ZCIsInVzZXJuYW1lIjoidGFtaXIxNDcifQ.dB1e1vAOO7WGoNqGakia1vv1cE4f222wHKjt36wvKok

{
    "user_name": "tamir147",
    "password": "tamir147"
}
