POST http://localhost:5252/account/transfer
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjA1MTQ1MDYsInVzZXJJZCI6IjY2ODkwMzRhYmJjNWU2ODdkZWUzNTk1ZSIsInVzZXJuYW1lIjoidGVzdDIifQ.kUZq1q2oQo-zc8TOBh_Yx5igg2Zo66PZHo3n_RZA69k


{
    "from": "66891bf758b33a533d32b470",
    "to": "668907a35ee2816599879215",
    "amount": 1500
}
