POST http://localhost:8080/account/transfer/6658a0f1ea724742549bc529
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTcwOTE2NDAsInVzZXJJZCI6IjY2NThhMGYxZWE3MjQ3NDI1NDliYzUyOSIsInVzZXJuYW1lIjoidGFtaXJFeDUifQ.kaoq-BaWMXFd4VAqF0u0-zkklDvgcs25z-XZKzfY2Eo

{
    "from_account_id": "6658a0f1ea724742549bc529",
    "to_account_id": "665722748a5f4995fe6fe619",
    "amount": 100.8
}
ß