POST http://localhost:8080/account/transfer/665e18f65a6ef02adf16af5d
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTc3MDIxMjgsInVzZXJJZCI6IjY2NWUxOGY2NWE2ZWYwMmFkZjE2YWY1ZCIsInVzZXJuYW1lIjoiSmhvbiJ9.6BGOB1HiBYEbrzviu_8mSJYyQp9Va-QBwDj1W8VMsog

{
    "from_account_id": "665e18f65a6ef02adf16af5d",
    "to_account_id": "665c2d14120cb97eb8b34d33",
    "amount": 1500
}
ß