definitions:
  api.AllTransactionsRes:
    properties:
      transactions:
        items:
          $ref: '#/definitions/db.Transaction'
        type: array
    type: object
  api.BalanceResponse:
    properties:
      balance:
        type: number
      transactions:
        items:
          $ref: '#/definitions/api.TransactionInfo'
        type: array
    type: object
  api.BankAccRes:
    properties:
      bank_account:
        $ref: '#/definitions/db.BankAccount'
    type: object
  api.BankAccsRes:
    properties:
      bankAccs:
        items:
          $ref: '#/definitions/db.BankAccount'
        type: array
    type: object
  api.CreateAccountRequest:
    properties:
      balance:
        type: number
      password:
        type: string
      phone_number:
        type: string
      user_name:
        type: string
    type: object
  api.DepositRequest:
    properties:
      _id:
        type: string
      amount:
        type: number
    type: object
  api.DepositResponse:
    properties:
      amount:
        type: number
      message:
        type: string
    type: object
  api.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  api.LoginRequest:
    properties:
      password:
        type: string
      user_name:
        type: string
    type: object
  api.LoginResponse:
    properties:
      token:
        type: string
      user_name:
        type: string
    type: object
  api.TransactionInfo:
    properties:
      amount:
        type: number
      from_account:
        type: string
    type: object
  api.TransferRequest:
    properties:
      amount:
        type: number
      from:
        type: string
      to:
        type: string
    type: object
  db.BankAccount:
    properties:
      accountHolder:
        type: string
      balance:
        type: number
      createdAt:
        type: string
      id:
        type: string
      password:
        type: string
      phoneNumber:
        type: string
      updatedAt:
        type: string
    type: object
  db.Transaction:
    properties:
      amount:
        type: number
      from_account:
        type: string
      id:
        type: string
      timestamp:
        type: string
      to_account:
        type: string
    type: object
info:
  contact: {}
  description: This is the main function that initializes the database, API manager,
    and starts the Gin server.
  title: gobank
  version: "1.0"
paths:
  /account/{id}:
    delete:
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: string
        "400":
          description: Invalid ID format
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Account not found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BearerAuth: []
    get:
      description: Get account details by its ID
      operationId: get-account-by-id
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Account found!
          schema:
            $ref: '#/definitions/api.BankAccRes'
        "400":
          description: Invalid ID format
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Account not found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get account by ID
  /account/balance:
    get:
      consumes:
      - application/json
      description: Check the balance of an account and list recent transactions
      parameters:
      - description: Account ID
        in: query
        name: accountId
        type: string
      - description: Account Holder Name
        in: query
        name: accountHolder
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.BalanceResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Check account balance
  /account/chatgpt:
    post:
      consumes:
      - application/json
      description: Handle a chat request using OpenAI GPT-3.5 model
      parameters:
      - description: User's text
        in: body
        name: user_text
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Handle chat request
  /account/deposit:
    post:
      consumes:
      - application/json
      description: Deposit a specified amount to an account
      parameters:
      - description: Deposit Request
        in: body
        name: deposit
        required: true
        schema:
          $ref: '#/definitions/api.DepositRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.DepositResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Error depositing to account
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Deposit to an account
  /account/name/{account_holder}:
    get:
      description: Retrieve account details by the account holder's name
      operationId: get-account-by-name-or-phone
      parameters:
      - description: Account Holder's Name
        in: query
        name: account_holder
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Account found!
          schema:
            $ref: '#/definitions/api.BankAccRes'
        "400":
          description: Invalid ID format
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Account not found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get account by account holder's name
  /account/transactions/{id}:
    get:
      description: Retrieve transaction history for a specific bank account
      operationId: get-transactions-history
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.AllTransactionsRes'
        "400":
          description: Invalid account ID format
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get transactions history for an account
  /account/transfer:
    post:
      consumes:
      - application/json
      description: Transfer funds from one bank account to another
      operationId: transfer-funds
      parameters:
      - description: Transfer Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.TransferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.BankAccRes'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Invalid account ID
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Transfer funds from one account to another
  /admin/accounts:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all accounts
      operationId: get-accounts
      produces:
      - application/json
      responses:
        "200":
          description: Accounts found
          schema:
            items:
              $ref: '#/definitions/api.BankAccsRes'
            type: array
        "500":
          description: Could not retrive accounts
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get all accounts
  /create:
    post:
      consumes:
      - application/json
      description: Create a new account with username and password
      operationId: create-account
      parameters:
      - description: Account Information
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/api.CreateAccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Account created!
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Create a new account
  /login:
    post:
      consumes:
      - application/json
      description: login your account via username and password
      operationId: login
      parameters:
      - description: Login Information
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/api.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.LoginResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Login your account
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
